"""corrected the foreign key att and added an Integer value i companyDev table

Revision ID: 2b10743f6218
Revises: 0f87c94b093f
Create Date: 2025-03-05 15:08:58.052821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b10743f6218'
down_revision = '0f87c94b093f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
