"""added pragma constrait

Revision ID: 6585dc1bb536
Revises: 89f835402024
Create Date: 2025-03-05 16:07:51.278940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6585dc1bb536'
down_revision = '89f835402024'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
