"""added pragma constrait

Revision ID: 89f835402024
Revises: 2b10743f6218
Create Date: 2025-03-05 16:06:59.556811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f835402024'
down_revision = '2b10743f6218'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
